# Generated by Django 4.0.2 on 2022-02-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_kg', models.CharField(max_length=50)),
                ('person_quantity', models.DecimalField(decimal_places=100, max_digits=100)),
                ('public_or_private', models.BooleanField(choices=[('Private', 'Private'), ('Public', 'Public')])),
                ('okpo', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='medical_officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
