# Generated by Django 4.0.2 on 2022-02-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_glavvrach_hospital_rename_medical_officer_lech_vrach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medsestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=90)),
                ('pincode_passport', models.DecimalField(decimal_places=0, default='0000', max_digits=4)),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('phone_number', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=90)),
                ('pincode_passport', models.DecimalField(decimal_places=0, default='0000', max_digits=4)),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('reason', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='lech_vrach',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='lech_vrach',
            name='full_name',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='lech_vrach',
            name='napravlenie',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='lech_vrach',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='lech_vrach',
            name='pincode_passport',
            field=models.DecimalField(decimal_places=0, default='0000', max_digits=4),
        ),
        migrations.AddField(
            model_name='lech_vrach',
            name='vybor',
            field=models.CharField(choices=[('Terapevt', 'Terapevt'), ('Hirurg', 'Hirurg')], default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='lech_vrach',
            name='work_experience',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glavvrach',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='glavvrach',
            name='full_name',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='glavvrach',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='glavvrach',
            name='pincode_passport',
            field=models.DecimalField(decimal_places=0, default='0000', max_digits=4),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='public_or_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='region_kg',
            field=models.CharField(choices=[('Bishkek', 'Bishkek'), ('Osh', 'Osh'), ('Naryn', 'Naryn')], max_length=50),
        ),
    ]
